function lfda_display( X, Y, T, Z, r, classes, class_names )
% Input:
%    X:      d x n matrix of original samples
%            d --- dimensionality of original samples
%            n --- the number of samples 
%    Y:      n dimensional vector of class labels
%    T: d x r transformation matrix (Z=T'*X)
%    Z: r x n matrix of dimensionality reduced samples 
%
%   Code generated by:
% (c) Masashi Sugiyama, Department of Compter Science, Tokyo Institute of Technology, Japan.
%     sugi@cs.titech.ac.jp,     http://sugiyama-www.cs.titech.ac.jp/~sugi/software/LFDA/
%%%%%%%%%%%%%%%%%%%%%% Displaying original 2D data
figure,
clf
hold on

if nargin < 5;
    r = 1;
end

if nargin < 6;
    classes = [1,2];
end

if nargin < 7;
    class_names = {'Task 1','Task 2'};
end
feat = [99,112];
set(gca,'FontName','Helvetica')
set(gca,'FontSize',12)
h=plot([-T(feat(1),r) T(feat(1),r)]*100,[-T(feat(2),r) T(feat(2),r)]*100,'k-','LineWidth',2);
h=plot(X(feat(1),Y==classes(1)),X(feat(2),Y==classes(1)),'bo');
h=plot(X(feat(1),Y==classes(2)),X(feat(2),Y==classes(2)),'rx');
legend('1D LFDA subspace',class_names{1},class_names{2})
axis equal
axis([-5 5 -5 5])
title('Original 2D data and subspace found by LFDA')
xlabel([num2str(feat(1)) '^t^h Feature']); ylabel([num2str(feat(2)) '^t^h Feature'])
set(gcf,'PaperUnits','centimeters');
set(gcf,'PaperPosition',[0 0 12 12]);

%%%%%%%%%%%%%%%%%%%%%% Displaying projected data
figure,
clf

subplot(2,1,1)
hold on
set(gca,'FontName','Helvetica')
set(gca,'FontSize',12)
hist(Z(Y==classes(1)),linspace(min(Z(r,:)),max(Z(r,:)),50));
h=get(gca,'Children');
set(h,'FaceColor','b')
axis([min(Z(r,:)) max(Z(r,:)) 0 inf])
title('Data projected onto 1D LFDA subspace')
xlabel(class_names{1})

subplot(2,1,2)
hold on
set(gca,'FontName','Helvetica')
set(gca,'FontSize',12)
hist(Z(Y==classes(2)),linspace(min(Z(r,:)),max(Z(r,:)),50));
h=get(gca,'Children');
set(h,'FaceColor','r')
axis([min(Z(r,:)) max(Z(r,:)) 0 inf])
xlabel(class_names{2})

set(gcf,'PaperUnits','centimeters');
set(gcf,'PaperPosition',[0 0 12 12]);

end

